local M = {}
local Job = require("plenary.job")
local flatdb = require("db")
local db = flatdb("/home/n451/Plugins/rss.nvim/lua/data")

local xml2lua = require("xml")
local handler = require("tree")

local function find_root(tbl)
	-- TODO: handle tang.xml, generated by hexo
	return tbl.rss.channel.item, tbl.rss.channel.title
end

local function parse_xml(src)
	local hdlr = handler:new()
	local parser = xml2lua.parser(hdlr)
	parser:parse(src)
	return hdlr.root
end

---fetch xml from source and load them into db
---@param url any
---@param name string # name of the source
function M.update_feed(url, name)
	Job:new({
		command = "curl",
		args = { url },
		on_exit = function(self, code, signal) -- TODO: check signal
			if not db[name] then
				db[name] = {}
			end
			if not db.titles then
				db.titles = {}
			end
			local src
			if #self:result() > 3 then
				src = table.concat(self:result(), " ")
			else
				src = self:result()[2]
			end
			local root, feed = find_root(parse_xml(src))
			for i, item in ipairs(root) do
				-- print(vim.inspect(item))
				item.feed = feed
				item.tags = { "unread" } -- HACK:
				db[item.title] = item
				table.insert(db[name], item.title)
				table.insert(db.titles, item.title)
			end
			db:save()
		end,
	}):start()
end

-- TODO:  vim.notify("feeds all loaded")
-- TODO:  maybe use a process bar like fidget.nvim

return M
