local M = {}
local flatdb = require("rss.db")
local db = flatdb("/home/n451/Plugins/rss.nvim/lua/data")

local xml2lua = require("xml")
local handler = require("tree")

local function find_root(tbl)
	-- TODO: handle tang.xml, generated by hexo
	return tbl.rss.channel.item, tbl.rss.channel.title
end

local function parse_xml(src)
	local hdlr = handler:new()
	local parser = xml2lua.parser(hdlr)
	parser:parse(src)
	return hdlr.root
end

-- TODO: need this??
if not db.titles then
	db.titles = {}
end

---fetch xml from source and load them into db
---@param url any
---@param name string # name of the source
function M.update_feed(url, name)
	if not db[name] then
		db[name] = {}
	end
	local curl = require("rss.curl")
	curl.get({
		url = url,
		callback = function(res)
			if res.status ~= 200 then
				return
			end
			local src = res.body
			local root, feed = find_root(parse_xml(src))
			for _, item in ipairs(root) do
				-- print(vim.inspect(item))
				item.feed = feed
				item.tags = { unread = true } -- HACK:
				db[item.title] = item
				table.insert(db[name], item.title)
				table.insert(db.titles, item.title)
			end
			db:save()
		end,
	})
end

-- M.update_feed("https://blog.cnbang.net/feed/", "lim")

-- TODO:  vim.notify("feeds all loaded")
-- TODO:  maybe use a process bar like fidget.nvim

return M
