name: Run tests

on:
  push:
    branches-ignore: [sync, stable]
    paths: ["colors/**", "lua/**", "tests/**"]
  pull_request:
    branches-ignore: [sync, stable]
    paths: ["colors/**", "lua/**", "tests/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    name: Run tests
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        neovim_version: ["v0.10.4", "nightly"]
        include:
          - os: macos-latest
            neovim_version: v0.10.4
          - os: windows-latest
            neovim_version: v0.10.4
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest
      # Required to build tree-sitter parsers
      - name: Install tree-sitter CLI
        uses: baptiste0928/cargo-install@v3
        with:
          crate: tree-sitter-cli

      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"

      - uses: leafo/gh-actions-luarocks@v4

      - name: deps
        run: |
          luarocks install tree-sitter-xml --lua-version 5.1 --local

      - name: Run tests
        run: make test
