name: Run stylua
on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  check:
    name: Run stylua format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.PAT }}
          version: latest # NOTE: we recommend pinning to a specific version in case of formatting changes
          # CLI arguments
          args: --check .
