name: Run tests

on:
  push:
    branches-ignore: [ sync, stable ]
    paths: [ 'colors/**', 'lua/**', 'tests/**' ]
  pull_request:
    branches-ignore: [ sync, stable ]
    paths: [ 'colors/**', 'lua/**', 'tests/**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    name: Run tests
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        neovim_version: ['v0.10.2', 'nightly']
        include:
        - os: macos-latest
          neovim_version: v0.10.1
        - os: windows-latest
          neovim_version: v0.10.1
    runs-on: ${{ matrix.os }}


    steps:
      - name: Setup Lua
        uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.1"

      - name: Setup LuaRocks
        uses: hishamhm/gh-actions-luarocks@master

      - name: Install busted and nlua
        run: |
          luarocks build --local --lua-version=5.1
        shell: bash

      - uses: actions/checkout@v4
      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - name: Run tests
        run: make test
